# Schedule {-}

Topics for each class day, as well as links to the pre-class videos and slides,  are listed below.

Before each class, watch the pre-class video and answer the corresponding comprehension questions on Moodle.

## Tentative overall schedule {-}

Regression tasks: Weeks 2-5

- Topics: model evaluation, model building, nonparametric methods, tools for modeling nonlinearity

Classification tasks: Weeks 6-9

- Topics: model evaluation, logistic regression, tree-based methods, support vector methods

Unsupervised learning: Weeks 10-11

- Topics: principal components analysis, clustering

Other topics + project work time: Weeks 12-14

- Suggested topic: deep learning

## Week 2: 1/28 - 2/1 {-}

- **Monday:** Assumptions of linear regression ([Video](https://youtu.be/FFxUbXRuufM), [Slides](https://drive.google.com/file/d/1sXhuyKUHbKJlFtrNBgN2xLw1bu4mUplz/view?usp=sharing))    
    Related ISLR reading: Section 2.1 gives some general background that is not particular to linear regression assumptions but sets up some key foundational ideas.
- **Friday:** Model evaluation metrics for regression ([Video](https://youtu.be/knHWpnDSnp4), [Slides](https://drive.google.com/file/d/1W-I3yoq6Zdo_HctnjfMxny3mRJPsi2iX/view?usp=sharing))    
    Related ISLR reading: Sections 2.2.1-2.2.2 talk about MSE, training and test data, test error, cross-validation, and the bias-variance tradeoff. The bias-variance tradeoff will come up a little later in class, but feel free to preview the ideas now.


## Week 3: 2/4 - 2/8 {-}

- **Monday:** Cross-validation ([Video](https://youtu.be/kjyUjqlahV8), [Slides](https://drive.google.com/file/d/1TnelbFeESHz3nwwbdzFOlcbVL1vTRgOg/view?usp=sharing))    
    Related ISLR reading: Section 5.1 is devoted to cross-validation. See also Sections 2.2.1-2.2.2.
- **Wednesday:** We'll finish reviewing cross validation, then talk briefly about variable selection methods for **building models** ([Video](https://youtu.be/MExs9jBQrDM), [Slides](https://drive.google.com/file/d/1FjxtDLIX_VApYm9GQhUjb6qao43QjUHP/view?usp=sharing))    
    Related ISLR reading: Section 6.1
- **Friday:** Quiz 1. Remaining time will be left for working on homework.


## Week 4: 2/11 - 2/15 {-}

- **Monday:** Shrinkage/regularization methods for model building ([Video](https://youtu.be/R8WHvkXevsU), [Slides](https://drive.google.com/file/d/1t1N_oHfkuRNaobPQOV-yW_winDmpKGro/view?usp=sharing))    
    Related ISLR reading: Section 6.2
- **Wednesday:** Continue discussing shrinkage methods
- **Friday:** K-nearest neighbors regression and the bias-variance tradeoff ([Video](https://youtu.be/BvQVovMefsM), [Slides](https://drive.google.com/file/d/1CgOmRP6c_WDFfPyPz972rG-ivTTJqiLE/view?usp=sharing))    
    Related ISLR reading: Section 2.2.2 for the bias-variance tradeoff and Section 3.5 for K-nearest neighbors regression


## Week 5: 2/18 - 2/22 {-}

- **Monday:** Modeling nonlinear trends with natural splines ([Video](https://youtu.be/D06d88NLdR4), [Slides](https://drive.google.com/file/d/1DdLxf-qbzKNClSoeQNIVPW2xZILDK5Jk/view?usp=sharing))    
    Related ISLR reading: Sections 7.1-7.4
- **Wednesday:** Local regression and generalized additive models ([Video](https://youtu.be/0PQKHlwh49A), [Slides](https://drive.google.com/file/d/1-CMS6C6_0Jb_3_PbNgJrQYRCDWHEpuyB/view?usp=sharing))    
    Related ISLR reading: Sections 7.6-7.7
- **Friday:** Quiz 2. Remaining time for a review activity.


## Week 6: 2/25 - 3/1 {-}

- **Monday:** Logistic regression ([Video](https://youtu.be/_9_h4sl7W5A), [Slides](https://drive.google.com/file/d/1DbMFCoHuiVSGh9IxSpQNPRZ9lxQMAlzo/view?usp=sharing))    
    Related ISLR reading: Sections 4.1-4.3
- **Wednesday:** Finish up logistic regression. Using old tools in the classification setting    
    Related ISLR reading: Section 7.7.2 (GAMs for Classification Problems), pages 39-42 (KNN for classification)
- **Friday:** Decision trees ([Video](https://youtu.be/xPnbEG-B4rY), [Slides](https://drive.google.com/file/d/1yUDSUTK2kqBq9s8u51fT-fxle0Mj0Wae/view?usp=sharing))    
    Related ISLR reading: 8.1


## Week 7: 3/4 - 3/8 {-}

- **Monday:** Decision trees
- **Wednesday:** Bagging and random forests ([Video](https://youtu.be/841I7-imlVo), [Slides](https://drive.google.com/file/d/15XOjXyk7nXVzkuMLgnR16FK2zBHUiyjZ/view?usp=sharing))    
    Related ISLR reading: 8.2
- **Friday:** Quiz 3. Finish up bagging and random forests.

## Week 8: 3/11 - 3/15 {-}

Review & midterm exam

Happy Spring Break!

## Week 9: 3/25 - 3/29 {-}

- **Monday:** Review midterm exam, start thinking about final projects
- **Wednesday:** Support vector machines ([Video](https://youtu.be/Kbdhe-MSCUw), [Slides](https://drive.google.com/file/d/1eJ8kkKf1rVWb_e1JSjRZfGkqfyG5_uRi/view?usp=sharing))    
    Related ISLR reading: Sections 9.1-9.4
- **Friday:** No class - MSCS Capstone Days

## Week 10: 4/1 - 4/5 {-}

- **Monday:** Continue with support vector machines
- **Wednesday:** K-means clustering ([Video](https://youtu.be/X_AGAxAnuSs), [Slides](https://drive.google.com/file/d/1l7bHWauUSYzVxF7Iu5kcFLRTE-OpSqsG/view?usp=sharing))    
    Related ISLR reading: Section 10.3 (specifically 10.3.1 for K-means)
- **Friday:** Quiz 4. Hierarchical clustering ([Video](https://youtu.be/Kqc9biu31LA), [Slides](https://drive.google.com/file/d/1tA1b0_qUa3z3Cj0-XWsiJI690lMGcNRB/view?usp=sharing))    
    Related ISLR reading: Section 10.3 (specifically 10.3.2 for hierarchical clustering)

## Week 11: 4/8 - 4/12 {-}

- **Monday:** Wrap up clustering
- **Wednesday:** Principal components analysis ([Video](https://youtu.be/x4_XTBoxr3Q), [Slides](https://drive.google.com/file/d/1mg7QT6aFmBWUm9lBOLQnBHt47Cwfs2uZ/view?usp=sharing))    
    Related ISLR reading: Section 10.2
- **Friday:** Wrap up PCA

## Week 12: 4/15 - 4/19 {-}

- This week is an introduction to deep learning: [Slides](https://drive.google.com/file/d/1FOh7P-cREypl_r5zAZtH0rCfcq5LM_XR/view?usp=sharing)






